"""Updated project structure

Revision ID: df82dde27d77
Revises: 9c20ba191e47
Create Date: 2025-02-24 02:04:12.411589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df82dde27d77'
down_revision = '9c20ba191e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.drop_column('tasks')
        batch_op.drop_column('attachments')
        batch_op.drop_column('comments')
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('comments', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attachments', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tasks', mysql.JSON(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
